In [3]:
import pandas as pd 
import sqlite3

In [4]:
conn = sqlite3.connect("Students.DB")
client = conn.cursor()

In [5]:
#SQL COMMAND
query = """CREATE TABLE IF NOT EXISTS timetable(
    TIME TEXT,
    MONDAY TEXT,
    TUESDAY TEXT,
    WEDNESDAY TEXT,
    THURSDAY TEXT,
    FRIDAY TEXT,
    SATURDAY TEXT,
    SUNDAY TEXT)
    """

In [6]:
client.execute(query)

In [7]:
conn.commit()

In [8]:
#timetable
rows = [

    ('9-10', 'DBMS', 'ML', 'OOPS', 'DBMS LAB', 'FREE', 'SPORTS', 'HOLIDAY'),

    ('10-11', 'OOPS', 'DBMS', 'ML', 'FREE', 'ML LAB', 'FREE', 'HOLIDAY'),

    ('11-12', 'ML', 'OOPS', 'DBMS', 'ML LAB', 'DBMS', 'FREE', 'HOLIDAY')

]

In [9]:
client.execute("DELETE FROM timetable")
conn.commit()


#inserting the data 
for row in rows:

    client.execute("""
    INSERT INTO timetable
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """, row)

In [10]:
timetable = pd.read_sql_query("""
                                SELECT * from timetable
                                """,conn)

In [11]:
timetable

    TIME MONDAY TUESDAY WEDNESDAY  THURSDAY  FRIDAY SATURDAY   SUNDAY
0   9-10   DBMS      ML      OOPS  DBMS LAB    FREE   SPORTS  HOLIDAY
1  10-11   OOPS    DBMS        ML      FREE  ML LAB     FREE  HOLIDAY
2  11-12     ML    OOPS      DBMS    ML LAB    DBMS     FREE  HOLIDAY

In [12]:
conn.commit()
conn.close()

In [13]:
conn = sqlite3.connect("Students.DB")
client = conn.cursor()

In [14]:
attendance_log_query = """
                    CREATE TABLE IF NOT EXISTS attendance_log(
                    DATE TEXT,
                    SUBJECT TEXT,
                    PRESENT BOOLEAN,
                    
                    UNIQUE(DATE, SUBJECT)
                    )
                    """

In [15]:
client.execute(attendance_log_query)
conn.commit()

In [16]:
attendanceLOG = pd.read_sql_query("""
                                SELECT * from attendance_log
                                """,conn)

In [17]:

attendanceLOG

         DATE SUBJECT  PRESENT
0  2026-05-26      ML        1
1  2026-05-26    DBMS        1
2  2026-05-26    OOPS        0

In [ ]:

Track_table

  SUBJECT  total_attendence  attended  PERCENTAGE
0    DBMS                 1         1         100
1      ML                 1         1         100
2    OOPS                 1         0           0